services:
  db: # Service name. It can be anything
    image: postgres:17
    container_name: weather-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analytics_db
    ports:
      - "5433:5432"
    volumes:
      # PostgreSQL Docker image stores database files in this directory.
      # Source: https://github.com/docker-library/docs/blob/master/postgres/content.md#pgdata
      - weather-postgres-data:/var/lib/postgresql/data

volumes:
  weather-postgres-data:
    name: weather-postgres-data
    