services:
  app: # Service name. It can be anything.
    build: # Build the image for the app service from a Dockerfile.
      context: . # Use the project root as the build context.
      dockerfile: 03_docker/Dockerfile
    container_name: weather-app # Custom name for the app container.
    working_dir: /app # Run commands from this directory inside the container.
    env_file:
      - .env
    volumes:
      - .:/app # Mount the project root from the host into /app inside the container.
    command: python 01_scripts/docker_postgres_connection_test.py # Run this py script when container runs.
    depends_on:
      - db # Start the db service before starting the app service.

  db: 
    image: postgres:17
    container_name: weather-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_POSTGRES_PORT}:${DB_PORT}"
    volumes:
      # PostgreSQL Docker image stores database files in this directory.
      # Source: https://github.com/docker-library/docs/blob/master/postgres/content.md#pgdata
      - weather-postgres-data:/var/lib/postgresql/data

volumes:
  weather-postgres-data:
    name: weather-postgres-data
    