services:
  app: # Service name. It can be anything.
    build: # Build the image for the app service from a Dockerfile.
      context: . # Use the project root as the build context.
      dockerfile: 03_docker/Dockerfile
    container_name: weather-app # Custom name for the app container.
    working_dir: /app # Run commands from this directory inside the container.
    env_file:
      - .env
    volumes:
      - .:/app # Mount the project root from the host into /app inside the container.
    command: python 01_scripts/docker_postgres_connection_test.py # Run this py script when container runs.
    depends_on:
      db:
        condition: service_healthy # Start the db service before starting the app service.

  db: 
    image: postgres:17
    container_name: weather-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_POSTGRES_PORT}:${DB_PORT}"
    volumes:
      # PostgreSQL Docker image stores database files in this directory.
      # Source: https://github.com/docker-library/docs/blob/master/postgres/content.md#pgdata
      - weather-postgres-data:/var/lib/postgresql/data
    # Healthcheck verifies that PostgreSQL is ready before dependent services start.
    # CMD-SHELL runs the healthcheck command through the container shell.
    # pg_isready checks whether PostgreSQL is ready to accept connections.
    # -U ${POSTGRES_USER} specifies the PostgreSQL user used for the readiness check.
    # -d ${POSTGRES_DB} specifies the database checked by pg_isready.
    # -p ${DB_PORT} specifies the PostgreSQL port inside the container, usually 5432.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  init-db: # One-time service that initializes the database structure by running SQL scripts.
    image: postgres:17 # Use the PostgreSQL image because it includes the psql command-line client.
    container_name: weather-init-db
    working_dir: /app
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      psql -h db -p ${DB_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f 01_scripts/1_create_schemas.sql
      &&
      psql -h db -p ${DB_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f 01_scripts/2_ddl_bronze.sql
      &&
      psql -h db -p ${DB_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f 01_scripts/5_ddl_silver.sql
      &&
      psql -h db -p ${DB_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f 01_scripts/7_ddl_gold.sql
      "

  load-bronze:
    build:
      context: .
      dockerfile: 03_docker/Dockerfile
    image: weather-python
    working_dir: /app
    env_file:
      - .env
    depends_on:
      init-db:
        condition: service_completed_successfully
    command: python 01_scripts/4_load_bronze.py
    volumes:
      - .:/app

  load-silver:
    image: postgres:17
    container_name: weather-load-silver
    working_dir: /app
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      load-bronze:
        condition: service_completed_successfully
    command: >
      sh -c "
      psql -h db -p ${DB_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f 01_scripts/6_load_silver.sql
      "

volumes:
  weather-postgres-data:
    name: weather-postgres-data
    